package com.quran.rabiulqaloob.ui

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.view.isInvisible
import androidx.core.view.isVisible
import androidx.fragment.app.activityViewModels
import androidx.lifecycle.lifecycleScope
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.PagerSnapHelper
import androidx.recyclerview.widget.RecyclerView
import com.quran.rabiulqaloob.BaseFragment
import com.quran.rabiulqaloob.databinding.FragmentReaderBinding
import com.quran.rabiulqaloob.models.PageModel
import com.quran.rabiulqaloob.models.PageSubModel
import com.quran.rabiulqaloob.models.PlayerModel
import com.quran.rabiulqaloob.ui.viewmodels.PlayerViewModel
import com.quran.rabiulqaloob.utils.Constants
import com.quran.rabiulqaloob.utils.readJsonFromAssets
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class ReaderFragment : BaseFragment() {
    private val pageModels = ArrayList<PageModel>()
    private lateinit var binding: FragmentReaderBinding
    private var pageModel: PageModel? = null
    private val args: ReaderFragmentArgs by navArgs()
    private val playerViewModel by activityViewModels<PlayerViewModel>()
    private var playerModel: PlayerModel = PlayerModel()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        pageModels.add(PageModel("1", "", ""))
        pageModels.add(PageModel("2", "1", "Al-Faatiha"))
        pageModels.add(PageModel("3", "1", "Al-Baqara"))
        pageModels.add(
            PageModel(
                "4", "1", "Al-Baqara", pageSubModel = arrayListOf(
                    PageSubModel(
                        parentPage = 4,
                        itemNo = "1"
                    )
                )
            )
        )
        pageModels.add(PageModel("5", "1", "Al-Baqara"))
        pageModels.add(PageModel("6", "1", "Al-Baqara"))
        pageModels.add(PageModel("7", "1", "Al-Baqara"))
        pageModels.add(PageModel("8", "1", "Al-Baqara"))
        pageModels.add(PageModel("9", "1", "Al-Baqara"))
        pageModels.add(PageModel("10", "1", "Al-Baqara"))
        pageModels.add(PageModel("11", "1", "Al-Baqara"))
        pageModels.add(PageModel("12", "1", "Al-Baqara"))
        pageModels.add(PageModel("13", "1", "Al-Baqara"))
        pageModels.add(PageModel("14", "1", "Al-Baqara"))
        pageModels.add(PageModel("15", "1", "Al-Baqara"))
        pageModels.add(PageModel("16", "1", "Al-Baqara"))
        pageModels.add(PageModel("17", "1", "Al-Baqara"))
        pageModels.add(PageModel("18", "1", "Al-Baqara"))
        pageModels.add(PageModel("19", "1", "Al-Baqara"))
        pageModels.add(PageModel("20", "1", "Al-Baqara"))
        pageModels.add(PageModel("21", "2", "Al-Baqara"))
        pageModels.add(PageModel("22", "2", "Al-Baqara"))
        pageModels.add(PageModel("23", "2", "Al-Baqara"))
        pageModels.add(PageModel("24", "2", "Al-Baqara"))
        pageModels.add(PageModel("25", "2", "Al-Baqara"))
        pageModels.add(PageModel("26", "2", "Al-Baqara"))
        pageModels.add(PageModel("27", "2", "Al-Baqara"))
        pageModels.add(PageModel("28", "2", "Al-Baqara"))
        pageModels.add(PageModel("29", "2", "Al-Baqara"))
        pageModels.add(PageModel("30", "2", "Al-Baqara"))
        pageModels.add(PageModel("31", "2", "Al-Baqara"))
        pageModels.add(PageModel("32", "2", "Al-Baqara"))
        pageModels.add(PageModel("33", "2", "Al-Baqara"))
        pageModels.add(PageModel("34", "2", "Al-Baqara"))
        pageModels.add(PageModel("35", "2", "Al-Baqara"))
        pageModels.add(PageModel("36", "2", "Al-Baqara"))
        pageModels.add(PageModel("37", "2", "Al-Baqara"))
        pageModels.add(PageModel("38", "2", "Al-Baqara"))
        pageModels.add(PageModel("39", "3", "Al-Baqara"))
        pageModels.add(PageModel("40", "3", "Al-Baqara"))
        pageModels.add(PageModel("41", "3", "Al-Baqara"))
        pageModels.add(PageModel("42", "3", "Al-Baqara"))
        pageModels.add(PageModel("43", "3", "Al-Baqara"))
        pageModels.add(PageModel("44", "3", "Al-Baqara"))
        pageModels.add(PageModel("45", "3", "Al-Baqara"))
        pageModels.add(PageModel("46", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("47", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("48", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("49", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("50", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("51", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("52", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("53", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("54", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("55", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("56", "3", "Aal-i-Imraan"))
        pageModels.add(PageModel("57", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("58", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("59", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("60", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("61", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("62", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("63", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("64", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("65", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("66", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("67", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("68", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("69", "4", "Aal-i-Imraan"))
        pageModels.add(PageModel("70", "4", "An-Nisaa"))
        pageModels.add(PageModel("71", "4", "An-Nisaa"))
        pageModels.add(PageModel("72", "4", "An-Nisaa"))
        pageModels.add(PageModel("73", "4", "An-Nisaa"))
        pageModels.add(PageModel("74", "4", "An-Nisaa"))
        pageModels.add(PageModel("75", "5", "An-Nisaa"))
        pageModels.add(PageModel("76", "5", "An-Nisaa"))
        pageModels.add(PageModel("77", "5", "An-Nisaa"))
        pageModels.add(PageModel("78", "5", "An-Nisaa"))
        pageModels.add(PageModel("79", "5", "An-Nisaa"))
        pageModels.add(PageModel("80", "5", "An-Nisaa"))
        pageModels.add(PageModel("81", "5", "An-Nisaa"))
        pageModels.add(PageModel("82", "5", "An-Nisaa"))
        pageModels.add(PageModel("83", "5", "An-Nisaa"))
        pageModels.add(PageModel("84", "5", "An-Nisaa"))
        pageModels.add(PageModel("85", "5", "An-Nisaa"))
        pageModels.add(PageModel("86", "5", "An-Nisaa"))
        pageModels.add(PageModel("87", "5", "An-Nisaa"))
        pageModels.add(PageModel("88", "5", "An-Nisaa"))
        pageModels.add(PageModel("89", "5", "An-Nisaa"))
        pageModels.add(PageModel("90", "5", "An-Nisaa"))
        pageModels.add(PageModel("91", "5", "An-Nisaa"))
        pageModels.add(PageModel("92", "5", "An-Nisaa"))
        pageModels.add(PageModel("93", "5", "An-Nisaa"))
        pageModels.add(PageModel("94", "6", "An-Nisaa"))
        pageModels.add(PageModel("95", "6", "An-Nisaa"))
        pageModels.add(PageModel("96", "6", "An-Nisaa"))
        pageModels.add(PageModel("97", "6", "Al-Maaida"))
        pageModels.add(PageModel("98", "6", "Al-Maaida"))
        pageModels.add(PageModel("99", "6", "Al-Maaida"))
        pageModels.add(PageModel("100", "6", "Al-Maaida"))
        pageModels.add(PageModel("101", "6", "Al-Maaida"))
        pageModels.add(PageModel("102", "6", "Al-Maaida"))
        pageModels.add(PageModel("103", "6", "Al-Maaida"))
        pageModels.add(PageModel("104", "6", "Al-Maaida"))
        pageModels.add(PageModel("105", "6", "Al-Maaida"))
        pageModels.add(PageModel("106", "6", "Al-Maaida"))
        pageModels.add(PageModel("107", "6", "Al-Maaida"))
        pageModels.add(PageModel("108", "6", "Al-Maaida"))
        pageModels.add(PageModel("109", "6", "Al-Maaida"))
        pageModels.add(PageModel("110", "6", "Al-Maaida"))
        pageModels.add(PageModel("111", "7", "Al-Maaida"))
        pageModels.add(PageModel("112", "7", "Al-Maaida"))
        pageModels.add(PageModel("113", "7", "Al-Maaida"))
        pageModels.add(PageModel("114", "7", "Al-Maaida"))
        pageModels.add(PageModel("115", "7", "Al-Maaida"))
        pageModels.add(PageModel("116", "7", "Al-An'aam"))
        pageModels.add(PageModel("117", "7", "Al-An'aam"))
        pageModels.add(PageModel("118", "7", "Al-An'aam"))
        pageModels.add(PageModel("119", "7", "Al-An'aam"))
        pageModels.add(PageModel("120", "7", "Al-An'aam"))
        pageModels.add(PageModel("121", "7", "Al-An'aam"))
        pageModels.add(PageModel("122", "7", "Al-An'aam"))
        pageModels.add(PageModel("123", "7", "Al-An'aam"))
        pageModels.add(PageModel("124", "7", "Al-An'aam"))
        pageModels.add(PageModel("125", "7", "Al-An'aam"))
        pageModels.add(PageModel("126", "7", "Al-An'aam"))
        pageModels.add(PageModel("127", "7", "Al-An'aam"))
        pageModels.add(PageModel("128", "7", "Al-An'aam"))
        pageModels.add(PageModel("129", "8", "Al-An'aam"))
        pageModels.add(PageModel("130", "8", "Al-An'aam"))
        pageModels.add(PageModel("131", "8", "Al-An'aam"))
        pageModels.add(PageModel("132", "8", "Al-An'aam"))
        pageModels.add(PageModel("133", "8", "Al-An'aam"))
        pageModels.add(PageModel("134", "8", "Al-An'aam"))
        pageModels.add(PageModel("135", "8", "Al-An'aam"))
        pageModels.add(PageModel("136", "8", "Al-An'aam"))
        pageModels.add(PageModel("137", "8", "Al-A'raaf"))
        pageModels.add(PageModel("138", "8", "Al-A'raaf"))
        pageModels.add(PageModel("139", "8", "Al-A'raaf"))
        pageModels.add(PageModel("140", "8", "Al-A'raaf"))
        pageModels.add(PageModel("141", "8", "Al-A'raaf"))
        pageModels.add(PageModel("142", "8", "Al-A'raaf"))
        pageModels.add(PageModel("143", "8", "Al-A'raaf"))
        pageModels.add(PageModel("144", "8", "Al-A'raaf"))
        pageModels.add(PageModel("145", "8", "Al-A'raaf"))
        pageModels.add(PageModel("146", "8", "Al-A'raaf"))
        pageModels.add(PageModel("147", "9", "Al-A'raaf"))
        pageModels.add(PageModel("148", "9", "Al-A'raaf"))
        pageModels.add(PageModel("149", "9", "Al-A'raaf"))
        pageModels.add(PageModel("150", "9", "Al-A'raaf"))
        pageModels.add(PageModel("151", "9", "Al-A'raaf"))
        pageModels.add(PageModel("152", "9", "Al-A'raaf"))
        pageModels.add(PageModel("153", "9", "Al-A'raaf"))
        pageModels.add(PageModel("154", "9", "Al-A'raaf"))
        pageModels.add(PageModel("155", "9", "Al-A'raaf"))
        pageModels.add(PageModel("156", "9", "Al-A'raaf"))
        pageModels.add(PageModel("157", "9", "Al-A'raaf"))
        pageModels.add(PageModel("158", "9", "Al-A'raaf"))
        pageModels.add(PageModel("159", "9", "Al-A'raaf"))
        pageModels.add(PageModel("160", "9", "Al-Anfaal"))
        pageModels.add(PageModel("161", "9", "Al-Anfaal"))
        pageModels.add(PageModel("162", "9", "Al-Anfaal"))
        pageModels.add(PageModel("163", "9", "Al-Anfaal"))
        pageModels.add(PageModel("164", "9", "Al-Anfaal"))
        pageModels.add(PageModel("165", "10", "Al-Anfaal"))
        pageModels.add(PageModel("166", "10", "Al-Anfaal"))
        pageModels.add(PageModel("167", "10", "Al-Anfaal"))
        pageModels.add(PageModel("168", "10", "Al-Anfaal"))
        pageModels.add(PageModel("169", "10", "At-Tawba"))
        pageModels.add(PageModel("170", "10", "At-Tawba"))
        pageModels.add(PageModel("171", "10", "At-Tawba"))
        pageModels.add(PageModel("172", "10", "At-Tawba"))
        pageModels.add(PageModel("173", "10", "At-Tawba"))
        pageModels.add(PageModel("174", "10", "At-Tawba"))
        pageModels.add(PageModel("175", "10", "At-Tawba"))
        pageModels.add(PageModel("176", "10", "At-Tawba"))
        pageModels.add(PageModel("177", "10", "At-Tawba"))
        pageModels.add(PageModel("178", "10", "At-Tawba"))
        pageModels.add(PageModel("179", "10", "At-Tawba"))
        pageModels.add(PageModel("180", "10", "At-Tawba"))
        pageModels.add(PageModel("181", "10", "At-Tawba"))
        pageModels.add(PageModel("182", "10", "At-Tawba"))
        pageModels.add(PageModel("183", "11", "At-Tawba"))
        pageModels.add(PageModel("184", "11", "At-Tawba"))
        pageModels.add(PageModel("185", "11", "At-Tawba"))
        pageModels.add(PageModel("186", "11", "At-Tawba"))
        pageModels.add(PageModel("187", "11", "At-Tawba"))
        pageModels.add(PageModel("188", "11", "Yunus"))
        pageModels.add(PageModel("189", "11", "Yunus"))
        pageModels.add(PageModel("190", "11", "Yunus"))
        pageModels.add(PageModel("191", "11", "Yunus"))
        pageModels.add(PageModel("192", "11", "Yunus"))
        pageModels.add(PageModel("193", "11", "Yunus"))
        pageModels.add(PageModel("194", "11", "Yunus"))
        pageModels.add(PageModel("195", "11", "Yunus"))
        pageModels.add(PageModel("196", "11", "Yunus"))
        pageModels.add(PageModel("197", "11", "Yunus"))
        pageModels.add(PageModel("198", "11", "Yunus"))
        pageModels.add(PageModel("199", "11", "Yunus"))
        pageModels.add(PageModel("200", "11", "Hud"))
        pageModels.add(PageModel("201", "12", "Hud"))
        pageModels.add(PageModel("202", "12", "Hud"))
        pageModels.add(PageModel("203", "12", "Hud"))
        pageModels.add(PageModel("204", "12", "Hud"))
        pageModels.add(PageModel("205", "12", "Hud"))
        pageModels.add(PageModel("206", "12", "Hud"))
        pageModels.add(PageModel("207", "12", "Hud"))
        pageModels.add(PageModel("208", "12", "Hud"))
        pageModels.add(PageModel("209", "12", "Hud"))
        pageModels.add(PageModel("210", "12", "Hud"))
        pageModels.add(PageModel("211", "12", "Hud"))
        pageModels.add(PageModel("212", "12", "Hud"))
        pageModels.add(PageModel("213", "12", "Yusuf"))
        pageModels.add(PageModel("214", "12", "Yusuf"))
        pageModels.add(PageModel("215", "12", "Yusuf"))
        pageModels.add(PageModel("216", "12", "Yusuf"))
        pageModels.add(PageModel("217", "12", "Yusuf"))
        pageModels.add(PageModel("218", "12", "Yusuf"))
        pageModels.add(PageModel("219", "13", "Yusuf"))
        pageModels.add(PageModel("220", "13", "Yusuf"))
        pageModels.add(PageModel("221", "13", "Yusuf"))
        pageModels.add(PageModel("222", "13", "Yusuf"))
        pageModels.add(PageModel("223", "13", "Yusuf"))
        pageModels.add(PageModel("224", "13", "Yusuf"))
        pageModels.add(PageModel("225", "13", "Ar-Ra'd"))
        pageModels.add(PageModel("226", "13", "Ar-Ra'd"))
        pageModels.add(PageModel("227", "13", "Ar-Ra'd"))
        pageModels.add(PageModel("228", "13", "Ar-Ra'd"))
        pageModels.add(PageModel("229", "13", "Ar-Ra'd"))
        pageModels.add(PageModel("230", "13", "Ar-Ra'd"))
        pageModels.add(PageModel("231", "13", "Ibrahim"))
        pageModels.add(PageModel("232", "13", "Ibrahim"))
        pageModels.add(PageModel("233", "13", "Ibrahim"))
        pageModels.add(PageModel("234", "13", "Ibrahim"))
        pageModels.add(PageModel("235", "13", "Ibrahim"))
        pageModels.add(PageModel("236", "13", "An-Nahl"))
        pageModels.add(PageModel("237", "14", "An-Nahl"))
        pageModels.add(PageModel("238", "14", "An-Nahl"))
        pageModels.add(PageModel("239", "14", "An-Nahl"))
        pageModels.add(PageModel("240", "14", "An-Nahl"))
        pageModels.add(PageModel("241", "14", "An-Nahl"))
        pageModels.add(PageModel("242", "14", "An-Nahl"))
        pageModels.add(PageModel("243", "14", "An-Nahl"))
        pageModels.add(PageModel("244", "14", "An-Nahl"))
        pageModels.add(PageModel("245", "14", "An-Nahl"))
        pageModels.add(PageModel("246", "14", "An-Nahl"))
        pageModels.add(PageModel("247", "14", "An-Nahl"))
        pageModels.add(PageModel("248", "14", "An-Nahl"))
        pageModels.add(PageModel("249", "14", "An-Nahl"))
        pageModels.add(PageModel("250", "14", "An-Nahl"))
        pageModels.add(PageModel("251", "14", "An-Nahl"))
        pageModels.add(PageModel("252", "14", "An-Nahl"))
        pageModels.add(PageModel("253", "14", "An-Nahl"))
        pageModels.add(PageModel("254", "14", "An-Nahl"))
        pageModels.add(PageModel("255", "15", "Al-Israa"))
        pageModels.add(PageModel("256", "15", "Al-Israa"))
        pageModels.add(PageModel("257", "15", "Al-Israa"))
        pageModels.add(PageModel("258", "15", "Al-Israa"))
        pageModels.add(PageModel("259", "15", "Al-Israa"))
        pageModels.add(PageModel("260", "15", "Al-Israa"))
        pageModels.add(PageModel("261", "15", "Al-Israa"))
        pageModels.add(PageModel("262", "15", "Al-Israa"))
        pageModels.add(PageModel("263", "15", "Al-Israa"))
        pageModels.add(PageModel("264", "15", "Al-Israa"))
        pageModels.add(PageModel("265", "15", "Al-Kahf"))
        pageModels.add(PageModel("266", "15", "Al-Kahf"))
        pageModels.add(PageModel("267", "15", "Al-Kahf"))
        pageModels.add(PageModel("268", "15", "Al-Kahf"))
        pageModels.add(PageModel("269", "15", "Al-Kahf"))
        pageModels.add(PageModel("270", "15", "Al-Kahf"))
        pageModels.add(PageModel("271", "15", "Al-Kahf"))
        pageModels.add(PageModel("272", "15", "Al-Kahf"))
        pageModels.add(PageModel("273", "16", "Al-Kahf"))
        pageModels.add(PageModel("274", "16", "Al-Kahf"))
        pageModels.add(PageModel("275", "16", "Al-Kahf"))
        pageModels.add(PageModel("276", "16", "Maryam"))
        pageModels.add(PageModel("277", "16", "Maryam"))
        pageModels.add(PageModel("278", "16", "Maryam"))
        pageModels.add(PageModel("279", "16", "Maryam"))
        pageModels.add(PageModel("280", "16", "Maryam"))
        pageModels.add(PageModel("281", "16", "Maryam"))
        pageModels.add(PageModel("282", "16", "Taa-Haa"))
        pageModels.add(PageModel("283", "16", "Taa-Haa"))
        pageModels.add(PageModel("284", "16", "Taa-Haa"))
        pageModels.add(PageModel("285", "16", "Taa-Haa"))
        pageModels.add(PageModel("286", "16", "Taa-Haa"))
        pageModels.add(PageModel("287", "16", "Taa-Haa"))
        pageModels.add(PageModel("288", "16", "Taa-Haa"))
        pageModels.add(PageModel("289", "16", "Taa-Haa"))
        pageModels.add(PageModel("290", "16", "Taa-Haa"))
        pageModels.add(PageModel("291", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("292", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("293", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("294", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("295", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("296", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("297", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("298", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("299", "17", "Al-Anbiyaa"))
        pageModels.add(PageModel("300", "17", "Al-Hajj"))
        pageModels.add(PageModel("301", "17", "Al-Hajj"))
        pageModels.add(PageModel("302", "17", "Al-Hajj"))
        pageModels.add(PageModel("303", "17", "Al-Hajj"))
        pageModels.add(PageModel("304", "17", "Al-Hajj"))
        pageModels.add(PageModel("305", "17", "Al-Hajj"))
        pageModels.add(PageModel("306", "17", "Al-Hajj"))
        pageModels.add(PageModel("307", "17", "Al-Hajj"))
        pageModels.add(PageModel("308", "17", "Al-Hajj"))
        pageModels.add(PageModel("309", "18", "Al-Muminoon"))
        pageModels.add(PageModel("310", "18", "Al-Muminoon"))
        pageModels.add(PageModel("311", "18", "Al-Muminoon"))
        pageModels.add(PageModel("312", "18", "Al-Muminoon"))
        pageModels.add(PageModel("313", "18", "Al-Muminoon"))
        pageModels.add(PageModel("314", "18", "Al-Muminoon"))
        pageModels.add(PageModel("315", "18", "Al-Muminoon"))
        pageModels.add(PageModel("316", "18", "An-Noor"))
        pageModels.add(PageModel("317", "18", "An-Noor"))
        pageModels.add(PageModel("318", "18", "An-Noor"))
        pageModels.add(PageModel("319", "18", "An-Noor"))
        pageModels.add(PageModel("320", "18", "An-Noor"))
        pageModels.add(PageModel("321", "18", "An-Noor"))
        pageModels.add(PageModel("322", "18", "An-Noor"))
        pageModels.add(PageModel("323", "18", "An-Noor"))
        pageModels.add(PageModel("324", "18", "An-Noor"))
        pageModels.add(PageModel("325", "18", "Al-Furqaan"))
        pageModels.add(PageModel("326", "18", "Al-Furqaan"))
        pageModels.add(PageModel("327", "19", "Al-Furqaan"))
        pageModels.add(PageModel("328", "19", "Al-Furqaan"))
        pageModels.add(PageModel("329", "19", "Al-Furqaan"))
        pageModels.add(PageModel("330", "19", "Al-Furqaan"))
        pageModels.add(PageModel("331", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("332", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("333", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("334", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("335", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("336", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("337", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("338", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("339", "19", "Ash-Shu'araa"))
        pageModels.add(PageModel("340", "19", "An-Naml"))
        pageModels.add(PageModel("341", "19", "An-Naml"))
        pageModels.add(PageModel("342", "19", "An-Naml"))
        pageModels.add(PageModel("343", "19", "An-Naml"))
        pageModels.add(PageModel("344", "19", "An-Naml"))
        pageModels.add(PageModel("345", "20", "An-Naml"))
        pageModels.add(PageModel("346", "20", "An-Naml"))
        pageModels.add(PageModel("347", "20", "An-Naml"))
        pageModels.add(PageModel("348", "20", "Al-Qasas"))
        pageModels.add(PageModel("349", "20", "Al-Qasas"))
        pageModels.add(PageModel("350", "20", "Al-Qasas"))
        pageModels.add(PageModel("351", "20", "Al-Qasas"))
        pageModels.add(PageModel("352", "20", "Al-Qasas"))
        pageModels.add(PageModel("353", "20", "Al-Qasas"))
        pageModels.add(PageModel("354", "20", "Al-Qasas"))
        pageModels.add(PageModel("355", "20", "Al-Qasas"))
        pageModels.add(PageModel("356", "20", "Al-Qasas"))
        pageModels.add(PageModel("357", "20", "Al-Qasas"))
        pageModels.add(PageModel("358", "20", "Al-Ankaboot"))
        pageModels.add(PageModel("359", "20", "Al-Ankaboot"))
        pageModels.add(PageModel("360", "20", "Al-Ankaboot"))
        pageModels.add(PageModel("361", "20", "Al-Ankaboot"))
        pageModels.add(PageModel("362", "20", "Al-Ankaboot"))
        pageModels.add(PageModel("363", "21", "Al-Ankaboot"))
        pageModels.add(PageModel("364", "21", "Al-Ankaboot"))
        pageModels.add(PageModel("365", "21", "Ar-Room"))
        pageModels.add(PageModel("366", "21", "Ar-Room"))
        pageModels.add(PageModel("367", "21", "Ar-Room"))
        pageModels.add(PageModel("368", "21", "Ar-Room"))
        pageModels.add(PageModel("369", "21", "Ar-Room"))
        pageModels.add(PageModel("370", "21", "Ar-Room"))
        pageModels.add(PageModel("371", "21", "Luqman"))
        pageModels.add(PageModel("372", "21", "Luqman"))
        pageModels.add(PageModel("373", "21", "Luqman"))
        pageModels.add(PageModel("374", "21", "As-Sajda"))
        pageModels.add(PageModel("375", "21", "As-Sajda"))
        pageModels.add(PageModel("376", "21", "As-Sajda"))
        pageModels.add(PageModel("377", "21", "Al-Ahzaab"))
        pageModels.add(PageModel("378", "21", "Al-Ahzaab"))
        pageModels.add(PageModel("379", "21", "Al-Ahzaab"))
        pageModels.add(PageModel("380", "21", "Al-Ahzaab"))
        pageModels.add(PageModel("381", "22", "Al-Ahzaab"))
        pageModels.add(PageModel("382", "22", "Al-Ahzaab"))
        pageModels.add(PageModel("383", "22", "Al-Ahzaab"))
        pageModels.add(PageModel("384", "22", "Al-Ahzaab"))
        pageModels.add(PageModel("385", "22", "Al-Ahzaab"))
        pageModels.add(PageModel("386", "22", "Saba"))
        pageModels.add(PageModel("387", "22", "Saba"))
        pageModels.add(PageModel("388", "22", "Saba"))
        pageModels.add(PageModel("389", "22", "Saba"))
        pageModels.add(PageModel("390", "22", "Saba"))
        pageModels.add(PageModel("391", "22", "Saba"))
        pageModels.add(PageModel("392", "22", "Faatir"))
        pageModels.add(PageModel("393", "22", "Faatir"))
        pageModels.add(PageModel("394", "22", "Faatir"))
        pageModels.add(PageModel("395", "22", "Faatir"))
        pageModels.add(PageModel("396", "22", "Faatir"))
        pageModels.add(PageModel("397", "22", "Yaseen"))
        pageModels.add(PageModel("398", "22", "Yaseen"))
        pageModels.add(PageModel("399", "23", "Yaseen"))
        pageModels.add(PageModel("400", "23", "Yaseen"))
        pageModels.add(PageModel("401", "23", "Yaseen"))
        pageModels.add(PageModel("402", "23", "As-Saaffaat"))
        pageModels.add(PageModel("403", "23", "As-Saaffaat"))
        pageModels.add(PageModel("404", "23", "As-Saaffaat"))
        pageModels.add(PageModel("405", "23", "As-Saaffaat"))
        pageModels.add(PageModel("406", "23", "As-Saaffaat"))
        pageModels.add(PageModel("407", "23", "As-Saaffaat"))
        pageModels.add(PageModel("408", "23", "As-Saaffaat"))
        pageModels.add(PageModel("409", "23", "Saad"))
        pageModels.add(PageModel("410", "23", "Saad"))
        pageModels.add(PageModel("411", "23", "Saad"))
        pageModels.add(PageModel("412", "23", "Saad"))
        pageModels.add(PageModel("413", "23", "Az-Zumar"))
        pageModels.add(PageModel("414", "23", "Az-Zumar"))
        pageModels.add(PageModel("415", "23", "Az-Zumar"))
        pageModels.add(PageModel("416", "23", "Az-Zumar"))
        pageModels.add(PageModel("417", "24", "Az-Zumar"))
        pageModels.add(PageModel("418", "24", "Az-Zumar"))
        pageModels.add(PageModel("419", "24", "Az-Zumar"))
        pageModels.add(PageModel("420", "24", "Az-Zumar"))
        pageModels.add(PageModel("421", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("422", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("423", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("424", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("425", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("426", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("427", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("428", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("429", "24", "Al-Mu'minun"))
        pageModels.add(PageModel("430", "24", "Fussilat"))
        pageModels.add(PageModel("431", "24", "Fussilat"))
        pageModels.add(PageModel("432", "24", "Fussilat"))
        pageModels.add(PageModel("433", "24", "Fussilat"))
        pageModels.add(PageModel("434", "24", "Fussilat"))
        pageModels.add(PageModel("435", "25", "Ash-Shura"))
        pageModels.add(PageModel("436", "25", "Ash-Shura"))
        pageModels.add(PageModel("437", "25", "Ash-Shura"))
        pageModels.add(PageModel("438", "25", "Ash-Shura"))
        pageModels.add(PageModel("439", "25", "Ash-Shura"))
        pageModels.add(PageModel("440", "25", "Ash-Shura"))
        pageModels.add(PageModel("441", "25", "Az-Zukhruf"))
        pageModels.add(PageModel("442", "25", "Az-Zukhruf"))
        pageModels.add(PageModel("443", "25", "Az-Zukhruf"))
        pageModels.add(PageModel("444", "25", "Az-Zukhruf"))
        pageModels.add(PageModel("445", "25", "Az-Zukhruf"))
        pageModels.add(PageModel("446", "25", "Az-Zukhruf"))
        pageModels.add(PageModel("447", "25", "Ad-Dukhaan"))
        pageModels.add(PageModel("448", "25", "Ad-Dukhaan"))
        pageModels.add(PageModel("449", "25", "Al-Jaathiya"))
        pageModels.add(PageModel("450", "25", "Al-Jaathiya"))
        pageModels.add(PageModel("451", "25", "Al-Jaathiya"))
        pageModels.add(PageModel("452", "25", "Al-Jaathiya"))
        pageModels.add(PageModel("453", "26", "Al-Ahqaf"))
        pageModels.add(PageModel("454", "26", "Al-Ahqaf"))
        pageModels.add(PageModel("455", "26", "Al-Ahqaf"))
        pageModels.add(PageModel("456", "26", "Al-Ahqaf"))
        pageModels.add(PageModel("457", "26", "Muhammad"))
        pageModels.add(PageModel("458", "26", "Muhammad"))
        pageModels.add(PageModel("459", "26", "Muhammad"))
        pageModels.add(PageModel("460", "26", "Muhammad"))
        pageModels.add(PageModel("461", "26", "Al-Fath"))
        pageModels.add(PageModel("462", "26", "Al-Fath"))
        pageModels.add(PageModel("463", "26", "Al-Fath"))
        pageModels.add(PageModel("464", "26", "Al-Hujuraat"))
        pageModels.add(PageModel("465", "26", "Al-Hujuraat"))
        pageModels.add(PageModel("466", "26", "Al-Hujuraat"))
        pageModels.add(PageModel("467", "26", "Qaaf"))
        pageModels.add(PageModel("468", "26", "Qaaf"))
        pageModels.add(PageModel("469", "26", "Adh-Dhaariyat"))
        pageModels.add(PageModel("470", "26", "Adh-Dhaariyat"))
        pageModels.add(PageModel("471", "27", "Adh-Dhaariyat"))
        pageModels.add(PageModel("472", "27", "At-Tur"))
        pageModels.add(PageModel("473", "27", "At-Tur"))
        pageModels.add(PageModel("474", "27", "An-Najm"))
        pageModels.add(PageModel("475", "27", "An-Najm"))
        pageModels.add(PageModel("476", "27", "Al-Qamar"))
        pageModels.add(PageModel("477", "27", "Al-Qamar"))
        pageModels.add(PageModel("478", "27", "Al-Qamar"))
        pageModels.add(PageModel("479", "27", "Ar-Rahmaan"))
        pageModels.add(PageModel("480", "27", "Ar-Rahmaan"))
        pageModels.add(PageModel("481", "27", "Ar-Rahmaan"))
        pageModels.add(PageModel("482", "27", "Al-Waaqia"))
        pageModels.add(PageModel("483", "27", "Al-Waaqia"))
        pageModels.add(PageModel("484", "27", "Al-Waaqia"))
        pageModels.add(PageModel("485", "27", "Al-Hadid"))
        pageModels.add(PageModel("486", "27", "Al-Hadid"))
        pageModels.add(PageModel("487", "27", "Al-Hadid"))
        pageModels.add(PageModel("488", "27", "Al-Hadid"))
        pageModels.add(PageModel("489", "28", "Al-Mujaadila"))
        pageModels.add(PageModel("490", "28", "Al-Mujaadila"))
        pageModels.add(PageModel("491", "28", "Al-Mujaadila"))
        pageModels.add(PageModel("492", "28", "Al-Hashr"))
        pageModels.add(PageModel("493", "28", "Al-Hashr"))
        pageModels.add(PageModel("494", "28", "Al-Hashr"))
        pageModels.add(PageModel("495", "28", "Al-Hashr"))
        pageModels.add(PageModel("496", "28", "Al-Mumtahana"))
        pageModels.add(PageModel("497", "28", "Al-Mumtahana"))
        pageModels.add(PageModel("498", "28", "As-Saff"))
        pageModels.add(PageModel("499", "28", "As-Saff"))
        pageModels.add(PageModel("500", "28", "Al-Jumu'a"))
        pageModels.add(PageModel("501", "28", "Al-Munaafiqoon"))
        pageModels.add(PageModel("502", "28", "Al-Munaafiqoon"))
        pageModels.add(PageModel("503", "28", "At-Taghaabun"))
        pageModels.add(PageModel("504", "28", "At-Taghaabun"))
        pageModels.add(PageModel("505", "28", "At-Talaaq"))
        pageModels.add(PageModel("506", "28", "At-Talaaq"))
        pageModels.add(PageModel("507", "28", "At-Tahrim"))
        pageModels.add(PageModel("508", "28", "At-Tahrim"))
        pageModels.add(PageModel("509", "29", "Al-Mulk"))
        pageModels.add(PageModel("510", "29", "Al-Mulk"))
        pageModels.add(PageModel("511", "29", "Al-Qalam"))
        pageModels.add(PageModel("512", "29", "Al-Qalam"))
        pageModels.add(PageModel("513", "29", "Al-Haaqqa"))
        pageModels.add(PageModel("514", "29", "Al-Haaqqa"))
        pageModels.add(PageModel("515", "29", "Al-Ma'aarij"))
        pageModels.add(PageModel("516", "29", "Al-Ma'aarij"))
        pageModels.add(PageModel("517", "29", "Nooh"))
        pageModels.add(PageModel("518", "29", "Nooh"))
        pageModels.add(PageModel("519", "29", "Al-Jinn"))
        pageModels.add(PageModel("520", "29", "Al-Jinn"))
        pageModels.add(PageModel("521", "29", "Al-Muzzammil"))
        pageModels.add(PageModel("522", "29", "Al-Muddaththir"))
        pageModels.add(PageModel("523", "29", "Al-Muddaththir"))
        pageModels.add(PageModel("524", "29", "Al-Qiyaama"))
        pageModels.add(PageModel("525", "29", "Al-Insaan"))
        pageModels.add(PageModel("526", "29", "Al-Insaan"))
        pageModels.add(PageModel("527", "29", "Al-Mursalaat"))
        pageModels.add(PageModel("528", "29", "Al-Mursalaat"))
        pageModels.add(PageModel("529", "30", "An-Naba"))
        pageModels.add(PageModel("530", "30", "An-Naazi'aat"))
        pageModels.add(PageModel("531", "30", "Abasa"))
        pageModels.add(PageModel("532", "30", "Abasa"))
        pageModels.add(PageModel("533", "30", "At-Takwir, Al-Infitaar"))
        pageModels.add(PageModel("534", "30", "Al-Mutaffifin"))
        pageModels.add(PageModel("535", "30", "Al-Inshiqaaq"))
        pageModels.add(PageModel("536", "30", "Al-Burooj"))
        pageModels.add(PageModel("537", "30", "At-Taariq"))
        pageModels.add(PageModel("538", "30", "Al-A'laa, Al-Ghaashiya"))
        pageModels.add(PageModel("539", "30", "Al-Fajr"))
        pageModels.add(PageModel("540", "30", "Al-Balad"))
        pageModels.add(PageModel("541", "30", "Ash-Shams, Al-Lail"))
        pageModels.add(PageModel("542", "30", "Ad-Dhuhaa, Ash-Sharh"))
        pageModels.add(PageModel("543", "30", "At-Tin, Al-Alaq"))
        pageModels.add(PageModel("544", "30", "Al-Qadr, Al-Bayyina"))
        pageModels.add(PageModel("545", "30", "Az-Zalzala, Al-Aadiyaat, Al-Qaari'a"))
        pageModels.add(PageModel("546", "30", "At-Takaathur, Al-Asr, Al-Humaza"))
        pageModels.add(PageModel("547", "30", "Al-Fil, Quraish, Al-Maa'un, Al-Kawthar"))
        pageModels.add(PageModel("548", "30", "Al-Kaafiroon, An-Nasr, Al-Lahab, Al-Ikhlaas"))
        pageModels.add(PageModel("549", "30", "Al-Falaq, An-Naas"))
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        binding = FragmentReaderBinding.inflate(layoutInflater)
        binding.list = pageModels
        val pageSnapHelper = PagerSnapHelper()
        pageSnapHelper.attachToRecyclerView(binding.rvReader)
        binding.rvReader.scrollToPosition(
            args.position
        )
        val surahListing = requireActivity().readJsonFromAssets(
            "surah.json"
        )
        binding.rvReader.addOnScrollListener(object : RecyclerView.OnScrollListener() {
            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
                super.onScrolled(recyclerView, dx, dy)
                val linearLayoutManager = binding.rvReader.layoutManager as LinearLayoutManager
                val position = linearLayoutManager.findFirstCompletelyVisibleItemPosition()
                preferenceHelper.setInt(
                    Constants.CURRENT_READING_INDEX,
                    position
                )

                if (position != -1) {
                    checkVisibility()
                    pageModel = pageModels[position]
                    lifecycleScope.launch(Dispatchers.IO) {
                        val surahModel = surahListing.find {
                            it.englishName == pageModels[position].surahNames.split(",")[0]
                        }
                        preferenceHelper.setString(
                            Constants.SURAH_NAME,
                            surahModel?.name ?: ""
                        )
                    }
                    binding.tvJuzzNo.isInvisible = pageModels[position].juzzNo.isEmpty()
                    binding.tvSurahName.isInvisible = pageModels[position].surahNames.isEmpty()
                    binding.tvJuzzNo.text =
                        "Juzz # ${pageModels[position].juzzNo}, "
                    binding.tvPageNo.text =
                        "Page # ${pageModels[position].pageNo}"
                    binding.tvSurahName.text =
                        pageModels[position].surahNames
                }


            }
        })
        binding.bookmarkButton.setOnClickListener {
            pageModel?.let {
                findNavController().navigate(
                    ReaderFragmentDirections.actionReaderFragmentToCreateBookmarkDialog(
                        it
                    )
                )
            }

        }
        binding.btnBack.setOnClickListener {
            findNavController()
                .navigateUp()
        }
        binding.ivPlay.setOnClickListener {
            pageModel?.let { page ->

                val surahModel = surahListing.find {
                    it.englishName == page.surahNames.split(",")[0]
                }
                surahModel?.let {
                    preferenceHelper.setString(
                        Constants.SURAH_NUMBER,
                        it.number.toString()
                    )

                    playerViewModel.setPlayerModel(
                        PlayerModel(currentSurah = it.number.toString(), isPlayerShown = true)
                    )
                }
            }

        }
        setObserver()
        return binding.root
    }

    private fun setObserver() {
        playerViewModel.playerModel.observe(viewLifecycleOwner) {
            playerModel = it
            checkVisibility()
        }
    }

    private fun checkVisibility() {
        val position =
            (binding.rvReader.layoutManager as LinearLayoutManager).findFirstCompletelyVisibleItemPosition()
        if (position != -1) {
            binding.ivPlay.isVisible = pageModels[position].surahNames.isNotEmpty() &&
                if (position == 0) playerModel.isPlayerShown.not()
                else (pageModels[position].surahNames != pageModels[position - 1].surahNames) && playerModel.isPlayerShown.not()
        }
    }

}